# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/faceliveness',
                'doc_host': 'https://shar1pius.github.io',
                'git_url': 'https://github.com/shar1pius/faceliveness',
                'lib_path': 'faceliveness'},
  'syms': { 'faceliveness.data': { 'faceliveness.data.liveness_dataset': ('data.html#liveness_dataset', 'faceliveness/data.py'),
                                   'faceliveness.data.liveness_dataset.__init__': ( 'data.html#liveness_dataset.__init__',
                                                                                    'faceliveness/data.py'),
                                   'faceliveness.data.liveness_dataset.dataset': ( 'data.html#liveness_dataset.dataset',
                                                                                   'faceliveness/data.py')}}}
