# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_data.ipynb.

# %% auto 0
__all__ = ['liveness_dataset']

# %% ../nbs/00_data.ipynb 4
class liveness_dataset():
    def __init__(self, 
                        csvfile: str, # contains image location with labels
                        smoothing=True, # smmothing facotr for the loss fn 
                        transform=None # image transforms
                        ):
        self.data = pd.read_csv(csvfile)
        self.transform = transform
        self.label_weight = 0.99 if smoothing else 1.0

    def dataset(self):
        images = []
        labels = []

        for index in self.data.index:
            img_name = self.data.iloc[index]['name']
            # load image
            img = Image.open(img_name)

            # load label
            label = self.data.iloc[index]['label']

            if self.transform:
                img = self.transform(img)

            images.append(img)
            labels.append(label)

        labels = np.array(labels, dtype=np.float32)

        dataset = [[images[i], labels[i]] for i in range(len(images))]
        return dataset
